baseURL = 'https://blog.rouages.xyz/les-sans-voix-website/'
languageCode = 'en-us'

title = "Les Sans-Voix"
theme = "contrast"

[params]
  minimal = false
  excerpts = false
  description = "my blog"

[menu]
  [[menu.main]]
    identifier = "01-À_propos"
    name = "À propos"
    slug = "a-propos"
  [[menu.main]]
    identifier = "02-Le_film"
    name = "Le film"
    url = "/le-film/"
