   name: deploy

   on:
     push:
       branches: [ main ]

   jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.99.1"

      - name: package website
        run: make package
      
      - name: deploy website
        run: make deploy GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"